### PR TITLE
add shrek ascii image (please merge)

### PR DESCRIPTION
**Pull request by egorushque**
please merge

### CODE REVIEW

**Comment by slaviqueue** [comment]
sorry cannot merge without tests bruh

**Comment by egorushque** [comment]
> sorry cannot merge without tests bruh

understandable
have a nice day

**Comment by egorushque** [comment]
hey guy please merge

**Comment by egorushque** [comment]
# hey guy

## please merge

**Comment by slaviqueue** [comment]
привет егор

**Pull request closed without merging**
